### ISSUE TITLE
Reformat Tables

### ISSUE THREAD

**Issue by DrOverbuild** [chemconx/cornerstone_myo#5]
There currently is no border and everything is hard to read on mobile
![D108BED2-3731-459A-A6BA-A9DE8CA1EC38](https://user-images.githubusercontent.com/3422979/69991329-12a85000-150d-11ea-96e3-43d7f22775e2.png)

**Comment by DrOverbuild** [comment]
Additions to make:

```css
table {
    width: 100%;
}

tr {
    border-bottom: 1px #ddd solid;
}

td, th {
    padding-right: 1rem;
    padding-bottom: 0.5rem;
    padding-top: 0.5rem;
    /* Could also using spacing functions */
}

```

![Screen Shot 2021-01-26 at 11 43 30 AM](https://user-images.githubusercontent.com/3422979/105882819-b84d3700-5fcb-11eb-89e9-cae594b28185.png)
